[package]
name = "job-apply-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
dotenv = "0.15.0"
rand = "0.9.0"
tempfile = "3.17.1"
thirtyfour = "0.35.0"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
